### PR TITLE
Adding products icon and updating apps icon

### PR DESCRIPTION
**Pull request by michaelgamble**
# Changes made

- added products icon
- changed the product icon character code to the correct character code
- renamed view-grid-outline to apps

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
I think the filename is wrong for the products icon @michaelgamble

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
sorry @michaelgamble , can you make them consistently uppercase to match the rest?

**Review by michaelgamble — COMMENTED** [review]
fixed the character code to match the proper format

**Review by michaelgamble — COMMENTED** [review]
fixed the character code to match the proper format

**Review by matthewbirtch — APPROVED** [review]

**Pull request merged**
