### PR TITLE
add-logout-icon

### PR DESCRIPTION
**Pull request by matthewbirtch**
Adding the logout icon to the icon font....hoping to refine this later, but we need this in the mobile app pretty quickly

### CODE REVIEW

**Review by andrewbrown00 — APPROVED** [review]
Looks good @matthewbirtch 👍

**Comment by enahum** [comment]
I came across this by accident as @Rina-dsg share the icon name with me over a DM.

Obviously this means that the font needs to be updated for the mobile app.

I'm comenting here as it should not be that things are found by chance and proper communication should happen around this sort of things.

I'll make sure to update the font on mobile with the latest version that already includes this addition.

**Comment by enahum** [comment]
Btw: once "refined" that will require the font to be updated again, hopefully it will be communicated :)

**Comment by matthewbirtch** [comment]
> I'm comenting here as it should not be that things are found by chance and proper communication should happen around this sort of things.

We literally just added this icon in yesterday - based on Marina's request. So this wasn't really by chance.

Point taken though. We do need to have a better way to communicate updates to this font. I guess it was a lack of understanding on our part for how this font gets updated in the mobile app (and the web app for that matter).

Any ideas @enahum @andrewbrown00 for how we can better communicate updates to the font to ensure the right parties have that information?

**Comment by enahum** [comment]
> > I'm comenting here as it should not be that things are found by chance and proper communication should happen around this sort of things.
> 
> 
> 
> We literally just added this icon in yesterday - based on Marina's request. So this wasn't really by chance.
> 
> 
> 
> Point taken though. We do need to have a better way to communicate updates to this font. I guess it was a lack of understanding on our part for how this font gets updated in the mobile app (and the web app for that matter).
> 
> 
> 
> Any ideas @enahum @andrewbrown00 for how we can better communicate updates to the font to ensure the right parties have that information?

Truth of the matter is that Marina may have requested it and it got adeed, on the other hand she just shared an icon name with me (i did assume that is was already part of the font) then I came across a notification for this repo where I saw the name of the PR, so yes.. chance hehehhe

As for the ideas, once a new font is sbumitted, at least the dev that requires the font should be added as a reviewer, then at least that dev knows he needs to update the font file in whatever project they are working on.

Another idea would be to subscribe a channel in mattermost where this PR's are added or even better a post to the font file with and definition of the icons thatbit includes.

Not sure what else can be done

**Comment by matthewbirtch** [comment]
Thanks @enahum. I added you to the `Compass Design System` channel where we typically communicate that a new icon has been added. It would be awesome to post automatically in to this channel when the repo is updated, but that's a bit out of my depth. I'll ask Michel if that's something he thinks he could do

**Comment by andrewbrown00** [comment]
@enahum thanks for the ideas! 

Is there anything we could do to automatically update the font changes across the repos? I'm not sure if that would be a destructive action or not, but I see something like updating the fonts being more global than requiring us to notify individuals.

**Comment by enahum** [comment]
@andrewbrown00 that is definitely possible, execute some sort of CI to submit PR's to the repos that are using the font.

**Comment by andrewbrown00** [comment]
> @andrewbrown00 that is definitely possible, execute some sort of CI to submit PR's to the repos that are using the font.

@enahum is that something you'd like to do, or see who can help with making it happen?

**Comment by enahum** [comment]
@andrewbrown00 so it seems this package is published to npm, I do not know how the package update is triggered but if I add the package to the mobile app and then modify a local script we can identify that new icons have been added as there is a new version update of the package.

But that still needs to be informed somehow.

**Comment by andrewbrown00** [comment]
Thanks for the context @enahum. 

> But that still needs to be informed somehow.

Could we set a webhook to post to the `Compass Design System` channel when the script identifies there's a new version update of the package? Maybe we could set a `#new icons` hashtag to be included in the message to find the updates easily in the channel?

**Comment by enahum** [comment]
Maybe talk to the integrations team to add the webhook you are talking about?

for now, I've added the npm package to the mobile app, so at least it'll get updated if there is a new version when we bump dependencies on the project (normally that happens once a month, sometimes more)

**Pull request merged**
